name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - "index.html"
      - "templates/**"
      - "partials/**"
      - "sections/**"
      - "assets/**"
      - ".github/workflows/pages.yml"
      - "README.md"
  workflow_dispatch:

# Avoid overlapping deploys
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build (or prepare) site artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      # Optional Node build if a package.json exists (e.g., if later we add a bundler)
      - name: Setup Node (conditional)
        if: hashFiles('**/package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install deps (conditional)
        if: hashFiles('**/package.json') != ''
        run: npm ci

      - name: Build (conditional)
        if: hashFiles('**/package.json') != ''
        run: |
          if npm run | grep -q " build"; then
            npm run build
          else
            echo "No build script found; skipping."
          fi

      - name: Determine publish directory
        id: pubdir
        run: |
          if [ -d "dist" ]; then
            echo "dir=dist" >> "$GITHUB_OUTPUT"
          elif [ -d "public" ]; then
            echo "dir=public" >> "$GITHUB_OUTPUT"
          else
            echo "dir=." >> "$GITHUB_OUTPUT"
          fi
          echo "Publishing from: $(cat "$GITHUB_OUTPUT")"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.pubdir.outputs.dir }}

  deploy:
    name: Deploy to Pages
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
